service:
  name: webhook-beacon
#app: your-app-name
#tenant: your-tenant-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-1'} # Overwrite the default region used. Default is us-east-1
  runtime: nodejs10.x
  apiKeys: # List of API keys to be used by your service API Gateway REST API
    - ${env:BEACON_APIKEY} # you can hide it in a serverless variable

functions:
  hello:
    handler: handler.beacon
    events:
      - http:
          method: post
          path: add
